# packages/music_app_controller.yaml

input_select:
  airplay_devices:
    name: AirPlay Devices
    options:
      - "— Select —"
    initial: "— Select —"
    icon: mdi:cast-audio

script:
  set_airplay_devices:
    alias: Apply AirPlay Devices
    sequence:
      # If your integration supports select_source, keep this:
      - action: media_player.select_source
        target:
          entity_id: media_player.apple_music_player
        data:
          source: "{{ states('input_select.airplay_devices') }}"

      # Otherwise, use the entity service we added instead (single device in a list):
      # - action: media_player.set_selected_airplay_devices
      #   data:
      #     entity_id: media_player.apple_music_player
      #     devices: ["{{ states('input_select.airplay_devices') }}"]

automation:
  - id: airplay_list_sync
    alias: "Music App: sync AirPlay device list"
    mode: restart
    trigger:
      - platform: state
        entity_id: media_player.apple_music_player   # adjust if your entity_id differs
      - platform: homeassistant
        event: start
    action:
      - variables:
          # Prefer 'available_devices' if your integration exposes it.
          # Otherwise fall back to 'source_list'.
          devices: >
            {{ state_attr('media_player.apple_music_player', 'available_devices')
               or state_attr('media_player.apple_music_player', 'source_list')
               or [] }}
      - service: input_select.set_options
        target:
          entity_id: input_select.airplay_devices
        data:
          options: "{{ devices if devices|length > 0 else ['No devices found'] }}"